### ISSUE TITLE
Documentation hosted by github, bitbucket or ... ?

### ISSUE THREAD

**Issue by Kerollmops** [jmacdonald/luthor#3]
Hello,

I saw you create all the documentation for this lib and you don't host it.
I think you can follow this little tutorial to push your doc on a `github repository` (free): https://github.com/kmcallister/travis-doc-upload/blob/master/README.md

If you need help, feed this thread !
Have a good day ^^

**Comment by jmacdonald** [comment]
Thanks for this! I've decided to self host the docs; you can find them [here](http://jordanmacdonald.ca/rust/luthor/). After browsing the generated docs, I've realized that I need to create more crate and module level documentation. I'll update those shortly!

**Comment by Kerollmops** [comment]
Ok good ! ^^
